# Generated by Django 2.2 on 2021-02-26 19:20

from django.db import migrations


def generate_groups(apps, schema_editor):
    Group = apps.get_model('auth','Group')
    Group.objects.get_or_create(name = "Manager")
    Group.objects.get_or_create(name= "Employee")

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(generate_groups)
    ]
